type GenreDictionary = { [key: string]: number };

export const genreMap: GenreDictionary = {
	Any: 0,
	'General Knowledge': 9,
	Books: 10,
	Film: 11,
	Music: 12,
	Theatres: 13,
	Television: 14,
	'Video Games': 15,
	'Board Games': 16,
	'Nature Science': 17,
	'Computer Science': 18,
	Mathematics: 19,
	Mythology: 20,
	Sports: 21,
	Geography: 22,
	History: 23,
	Politics: 24,
	Art: 25,
	Celebrities: 26,
	Animals: 27,
	Vehicles: 28,
	Comics: 29,
	Gadgets: 30,
	'Anime & Manga': 31,
	'Cartoons & Animation': 32,
};
